### ISSUE TITLE
how splitIntoLines works!?

### ISSUE THREAD

**Issue by benxshen** [Zarel/vscode-sublime-commands#1]
Hi Zarel, 
Thank you for providing this convenient vscode plugin :)

I am not clear the function of 'splitIntoLines'. What will be split into lines? I tried single line, but no works.
I tried multiline selection also, I found it became multi-cursors put at the end of each line of sections.

**Comment by Zarel** [comment]
It works the same way as the Sublime Text "Split into Lines" (Cmd+Shift+L on Mac) command.

When you have a selection that spans multiple lines, it will split the selection into multiple selections, spanning one line each.

**Comment by denistsoi** [comment]
+1 "splitintolines" command doesn't work as in sublime;

**Comment by Zarel** [comment]
I'm closing, because so far no one's actually explained how it's different.
