### ISSUE TITLE
how can i add sublime cmd like (expand_selection) to vsc 

### ISSUE THREAD

**Issue by ToBeGeekBoy** [Zarel/vscode-sublime-commands#2]
1. sublime cmd like below, how can i add it to vsc?
{ "keys": ["ctrl+shift+space"], "command": "expand_selection", "args": {"to": "scope"} },

2.dose this plugin support all cmds from sublime text? if not, is there a list of cmds which are supported?

**Comment by Zarel** [comment]
Expand Selection is not supported.

The four commands that are supported are listed in the README:

https://github.com/Zarel/vscode-sublime-commands/blob/master/README.md

**Comment by ToBeGeekBoy** [comment]
Thank u for your reply.

I thought the plugin supports manny sublime commands.

Are you ganna support more  sublime cmds ?

发自 Smartisan M1

Guangcong Luo <notifications@github.com> 于 2018年1月29日 下午9:22写道：


Expand Selection is not supported.

The four commands that are supported are listed in the README:

https://github.com/Zarel/vscode-sublime-commands/blob/master/README.md

―

**Comment by Zarel** [comment]
I might, depending on if there are any that are popular and no one's implemented yet.

But Expand Selection is already a built-in command in VS Code. You can just change the keyboard shortcut normally.

**Comment by ToBeGeekBoy** [comment]
build-in cmd is not powerful enough, but i found a plugin what i want .


发自 Smartisan M1

Guangcong Luo <notifications@github.com> 于 2018年1月29日 下午10:07写道：


I might, depending on if there are any that are popular and no one's implemented yet.

But Expand Selection is already a built-in command in VS Code. You can just change the keyboard shortcut normally.

―
